---
title: "EDA"
output: html_document
---
```{r}
library(tidyverse)
library(ggridges)
```

make some plots

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = case_match(
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) |>
  select(name, id, everything())
```
```{r}
weather_df |> 
  ggplot(aes(x = prcp)) + 
  geom_histogram()
```

```{r}
weather_df |> 
  filter(prcp >= 1000)
```

```{r}
weather_df |> 
  filter(tmax >= 20, tmax <= 30) |> 
  ggplot(aes(x = tmin, y = tmax, color = name, shape = name)) + 
  geom_point(alpha = .75)
```
```{r}
weather_df |>
  group_by(name, month)
```
```{r}
weather_df |>
  group_by(name) |>
  summarize(n_obs = n(),
            n_dist = n_distinct(month))
#count(name)
```
```{r}
weather_df |>
  group_by(name, month) |>
  summarize(n_obs = n())
```

## 2x2
```{r}
weather_df |> 
  drop_na(tmax) |> 
  mutate(
    cold = case_when(
      tmax <  5 ~ "cold",
      tmax >= 5 ~ "not_cold"
  )) |> 
  filter(name != "Molokai_HI") |> 
  group_by(name, cold) |> 
  summarize(count = n())
```

```{r}
weather_df |>
  group_by(month) |>
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE),
    mean_prec = mean(prcp, na.rm = TRUE),
    median_tmax = median(tmax),
    sd_tmax = sd(tmax))
```

```{r}
weather_df |>
  group_by(name, month) |>
  summarize(
    mean_tmax = mean(tmax),
    median_tmax = median(tmax))
```

```{r}
weather_df |>
  group_by(name, month) |>
  summarize(across(tmin:prcp, mean))
```

```{r}
weather_df |>
  group_by(name, month) |>
  summarize(mean_tmax = mean(tmax, na.rm = TRUE)) |>
  ggplot(aes(x = month, y = mean_tmax, color = name)) + 
    geom_point() + geom_line() + 
    theme(legend.position = "bottom")
```
```{r}
weather_df |>
  group_by(name, month) |>
  summarize(mean_tmax = mean(tmax, na.rm = TRUE)) |> 
  pivot_wider(
    names_from = name,
    values_from = mean_tmax) |> 
  knitr::kable(digits = 2,
               col.names = c('Month','Central Park','Molokai','Waterhole'))
```

```{r}
weather_df |>
  group_by(name) |>
  mutate(
    mean_tmax = mean(tmax, na.rm = TRUE),
    centered_tmax = tmax - mean_tmax) |> 
  ggplot(aes(x = date, y = centered_tmax, color = name)) + 
    geom_point() 
```

```{r}
weather_df |>
  group_by(name, month) |>
  mutate(temp_ranking = min_rank(tmax))
```

```{r}
weather_df |>
  group_by(name, month) |>
  filter(min_rank(tmax) < 2)
```
```{r}
weather_df |>
  group_by(name, month) |>
  filter(min_rank(tmax) < 4)|>
  arrange(tmax)
```

```{r}
weather_df |>
  group_by(name) |>
  mutate(temp_change = tmax - lag(tmax))|>
  filter(min_rank(temp_change)<3)
```
```{r}
weather_df |>
  group_by(name) |>
  mutate(temp_change = tmax - lag(tmax)) |>
  summarize(
    temp_change_sd = sd(temp_change, na.rm = TRUE),
    temp_change_max = max(temp_change, na.rm = TRUE))
```

## pulse data

```{r}
library(haven)
pulse_df <- read_sas('public_pulse_data.sas7bdat')|>
  janitor::clean_names()|>
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = 'visit',
    values_to = "bdi_score",
    names_prefix = "bdi_score_"
  )|>
  group_by(visit)|>
  summarise(mean_bdi = mean(bdi_score, na.rm = T))|>
  knitr::kable(digits = 1)
```












